"""empty message

Revision ID: 63b8702d9e72
Revises: dda99c905203
Create Date: 2023-06-05 15:08:06.675397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b8702d9e72'
down_revision = 'dda99c905203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlock_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ucode_create_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ucode_valid_datetime', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_unlock_code_ucode_create_date')
        batch_op.drop_index('ix_unlock_code_ucode_valid_date')
        batch_op.create_index(batch_op.f('ix_unlock_code_ucode_create_datetime'), ['ucode_create_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_unlock_code_ucode_valid_datetime'), ['ucode_valid_datetime'], unique=False)
        batch_op.drop_column('ucode_create_date')
        batch_op.drop_column('ucode_valid_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlock_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ucode_valid_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('ucode_create_date', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_unlock_code_ucode_valid_datetime'))
        batch_op.drop_index(batch_op.f('ix_unlock_code_ucode_create_datetime'))
        batch_op.create_index('ix_unlock_code_ucode_valid_date', ['ucode_valid_date'], unique=False)
        batch_op.create_index('ix_unlock_code_ucode_create_date', ['ucode_create_date'], unique=False)
        batch_op.drop_column('ucode_valid_datetime')
        batch_op.drop_column('ucode_create_datetime')

    # ### end Alembic commands ###
