"""add package_info, access_warning table. Update relationship

Revision ID: 67b18e77159c
Revises: 
Create Date: 2023-05-25 20:02:07.707847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b18e77159c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locker_name', sa.String(length=64), nullable=False),
    sa.Column('locker_status', sa.Boolean(), nullable=True),
    sa.Column('unlock_code', sa.String(length=64), nullable=True),
    sa.Column('ucode_valid_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locker_locker_name'), ['locker_name'], unique=False)

    op.create_table('resident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resident_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_resident_phone'), ['phone'], unique=True)

    op.create_table('access_warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=128), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('locker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locker_id'], ['locker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('booking_valid_date', sa.DateTime(), nullable=True),
    sa.Column('booking_status', sa.Boolean(), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('locker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locker_id'], ['locker.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_order_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_order_booking_valid_date'), ['booking_valid_date'], unique=False)

    op.create_table('package_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('locker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locker_id'], ['locker.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_info_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_info_pickup_date'), ['pickup_date'], unique=False)

    op.create_table('booking_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bcode_name', sa.String(length=64), nullable=False),
    sa.Column('bcode_valid_date', sa.DateTime(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_code_bcode_name'), ['bcode_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_code_bcode_valid_date'), ['bcode_valid_date'], unique=False)

    op.create_table('booking_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bcode_name', sa.String(length=64), nullable=False),
    sa.Column('locker_name', sa.String(length=64), nullable=False),
    sa.Column('unlock_code', sa.String(length=64), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_history_bcode_name'), ['bcode_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_history_locker_name'), ['locker_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_history_locker_name'))
        batch_op.drop_index(batch_op.f('ix_booking_history_bcode_name'))

    op.drop_table('booking_history')
    with op.batch_alter_table('booking_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_code_bcode_valid_date'))
        batch_op.drop_index(batch_op.f('ix_booking_code_bcode_name'))

    op.drop_table('booking_code')
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_info_pickup_date'))
        batch_op.drop_index(batch_op.f('ix_package_info_delivery_date'))

    op.drop_table('package_info')
    with op.batch_alter_table('booking_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_order_booking_valid_date'))
        batch_op.drop_index(batch_op.f('ix_booking_order_booking_date'))

    op.drop_table('booking_order')
    op.drop_table('access_warning')
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resident_phone'))
        batch_op.drop_index(batch_op.f('ix_resident_email'))

    op.drop_table('resident')
    with op.batch_alter_table('locker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locker_locker_name'))

    op.drop_table('locker')
    # ### end Alembic commands ###
