"""delete package_info table

Revision ID: 8ca8454bb12c
Revises: a48bc8717000
Create Date: 2023-05-29 20:02:58.250395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca8454bb12c'
down_revision = 'a48bc8717000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.drop_index('ix_package_info_delivery_date')
        batch_op.drop_index('ix_package_info_pickup_date')

    op.drop_table('package_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('delivery_date', sa.DATETIME(), nullable=True),
    sa.Column('pickup_date', sa.DATETIME(), nullable=True),
    sa.Column('resident_id', sa.INTEGER(), nullable=True),
    sa.Column('locker_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['locker_id'], ['locker.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.create_index('ix_package_info_pickup_date', ['pickup_date'], unique=False)
        batch_op.create_index('ix_package_info_delivery_date', ['delivery_date'], unique=False)

    # ### end Alembic commands ###
