"""update booking code table

Revision ID: a101cd2541c3
Revises: 527b459de6c9
Create Date: 2023-05-29 20:46:16.246126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a101cd2541c3'
down_revision = '527b459de6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bcode_create_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_booking_code_bcode_create_date'), ['bcode_create_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_code_bcode_create_date'))
        batch_op.drop_column('bcode_create_date')

    # ### end Alembic commands ###
