"""change locker table

Revision ID: a48bc8717000
Revises: 67b18e77159c
Create Date: 2023-05-29 20:02:29.453918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48bc8717000'
down_revision = '67b18e77159c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locker', schema=None) as batch_op:
        batch_op.drop_column('ucode_valid_date')
        batch_op.drop_column('unlock_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlock_code', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('ucode_valid_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
